In [1]:
import numpy as np

from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

In [2]:
from sklearn.datasets import load_iris
iris = load_iris()

In [3]:
#Logistic Regression
logreg_scores = cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'), iris.data, iris.target, cv = 3)
logreg_scores , np.average(logreg_scores)

(array([0.96, 0.96, 0.94]), 0.9533333333333333)

In [4]:
#Decision Tree
dectree_scores = cross_val_score(DecisionTreeClassifier(), iris.data, iris.target, cv = 3)
dectree_scores , np.average(dectree_scores)

(array([0.98, 0.92, 0.98]), 0.96)

In [5]:
#SVM
svm_scores = cross_val_score(SVC(), iris.data, iris.target, cv = 3)
svm_scores ,  np.average(svm_scores)

(array([0.96, 0.98, 0.94]), 0.96)

In [6]:
#Random Forest
ranfor_scores = cross_val_score(RandomForestClassifier(n_estimators = 50), iris.data, iris.target, cv = 3)
ranfor_scores , np.average(ranfor_scores)

(array([0.98, 0.94, 0.96]), 0.96)

### Random Forest gives the highest score.

In [8]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [9]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

scores_logreg = []
scores_dectree = []
scores_svm = []
scores_ranfor = []

for train_index, test_index in folds.split(iris.data, iris.target):
    X_train, X_test, y_train, y_test = iris.data[train_index], iris.data[test_index], iris.target[train_index], iris.target[test_index]
                                       
    scores_logreg.append(get_score(LogisticRegression(solver='liblinear',multi_class='ovr'), X_train, X_test, y_train, y_test))
    scores_dectree.append(get_score(DecisionTreeClassifier(), X_train, X_test, y_train, y_test))
    scores_svm.append(get_score(SVC(gamma='auto'), X_train, X_test, y_train, y_test))
    scores_ranfor.append(get_score(RandomForestClassifier(n_estimators=40), X_train, X_test, y_train, y_test))

In [10]:
scores_logreg , scores_dectree , scores_svm , scores_ranfor

([0.96, 0.96, 0.94], [0.98, 0.94, 1.0], [0.98, 0.98, 0.96], [0.98, 0.94, 0.96])

In [11]:
np.average(scores_logreg) , np.average(scores_dectree) , np.average(scores_svm), np.average(scores_ranfor)

(0.9533333333333333, 0.9733333333333333, 0.9733333333333333, 0.96)